---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp3
 labels:
  app: myapp3
spec:
 replicas: 2
 selector:
  matchLabels:
   app: myapp3
 template:
  metadata:
   labels:
    app: myapp3
  spec:
   containers:
   - name: myapp3
     image: deepudondocker/kube8s:tagversion
     command: ["echo", "success"]
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp3
spec:
  type: LoadBalancer
  selector:
    app: myapp3
  ports:
    - protocol: TCP
      port: 5611
      targetPort: 8080
